server.port=${PORT:8080}

spring.application.name=taskcollab

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

app.jwt.secret=Q2hhbmdlVGhpc1RleHRUb0EgU3Ryb25nU2VjcmV0S2V5MTIzNDU2Nzg5MA==
app.jwt.expiration-ms=3600000

app.frontend.url=${FRONTEND_URL:http://localhost:5173}
